// <auto-generated />
namespace MySql.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class sermondateunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sermondateunique));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051242195_sermon date unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
